### ISSUE TITLE
Sync the View between the Clients

### ISSUE THREAD

**Issue by Kampii** [DigitalSlideArchive/openseadragon-annotations#4]
You had this nice page where two windows would be in sync while zooming in/out and panning. Could we take it one step further and sync between the clients? If I could have some source code I could google and play with it and see if it is doable.

<img width="953" alt="screenshot 2015-11-12 18 47 45" src="https://cloud.githubusercontent.com/assets/725316/11137578/fd733b2a-896d-11e5-9b6f-14d42b5b2ca5.png">

**Comment by mohammedkhalilia** [comment]
Moved everything to AngularJS
